# Generated by Django 5.2.3 on 2025-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_customer_supplier_alter_items_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/suppliers/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
